name: GCC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # 22.04 required for latest compiler versions
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler:
          - g++-13
        build_type: [ Debug, Release ]
        dont_use_std_vector: [ ON, OFF ]
        dont_use_std_string: [ ON, OFF ]
        exclude:
          # gcc-13's constexpr string implementation has bugs: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105440
          - compiler: g++-13
            dont_use_std_string: OFF
        include:
          - compiler: g++-13
            required_pkgs: g++-13

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa &&
          sudo apt update &&
          sudo apt-get install -y ${{matrix.required_pkgs}}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build
          -D CMAKE_BUILD_TYPE=${{matrix.build_type}}
          -D BUGSPRAY_DONT_USE_STD_VECTOR=${{matrix.dont_use_std_vector}}
          -D BUGSPRAY_DONT_USE_STD_STRING=${{matrix.dont_use_std_string}}
          -D ERR_BUILD_TESTS=ON
          -D CMAKE_CXX_COMPILER=${{matrix.compiler}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
      
